### PR TITLE
service annotations section

### PR DESCRIPTION
**Pull request by franeksaww**

### CODE REVIEW

**Comment by franeksaww** [comment]
@jason2506 @weihanglo

**Comment by weihanglo** [comment]
Great improvement! Thanks for your contribution. We'll merge this pull request into develop branch and make a new release ASAP. 🚀

**Comment by franeksaww** [comment]
@weihanglo @jason2506 It works, but I have one question - how can I send metric manually to prometheus-statsd-exporter? I am trying different ways and I am missing something important for sure :/

**Comment by weihanglo** [comment]
@franeksaww 

This helm chart is just a wrapper around the offical [statsd_exporter](https://github.com/prometheus/statsd_exporter), which collects metrics from any StatsD environment. Our use case is scraping instrument information from [gunicorn servers via StatsD protocol](https://docs.gunicorn.org/en/stable/instrumentation.html).

Underneath the hood, this chart creates [a statsd_exporter deployment](https://github.com/hahow/prometheus-statsd-exporter/blob/a847737/templates/deployment.yaml) and exposes [a service](https://github.com/hahow/prometheus-statsd-exporter/blob/a847737/templates/service.yaml) for it. Hence, to gather metrics from your StatsD client, just configure your Prometheus rules to scrape metrics from the service. Moreover, if you use [Prometheus Operator](https://github.com/prometheus-operator/prometheus-operator), enabling the [service monitor](https://github.com/hahow/prometheus-statsd-exporter/blob/a7f55d4cd9cde9d1f44cb87309e08bf9b13640ea/values.yaml#L98-L103) would make your life easily 😂.

**Review by jason2506 — APPROVED** [review]

**Pull request merged**
